apiVersion: v1
entries:
  owc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-12-16T14:34:07.3329753+01:00"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 9a03e3933e8bbab8e587ee9a8b70b290e4b49d990febe6441d9a3ec8e3106ac0
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: owc
    urls:
    - owc-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-16T14:34:07.3281381+01:00"
